const now = require('now-env');

const {
	BOT_URL,
	TELEGRAM_API,
	BINANCE_API,
	BINANCE_API_SECRET,
} = process.env;

module.exports = {
	BOT_URL: BOT_URL,
	TELEGRAM_API: TELEGRAM_API,
	BINANCE_API: BINANCE_API,
	BINANCE_API_SECRET: BINANCE_API_SECRET,
}
